name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Source Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true

      - name: Install Dependencies
        run: vp install --frozen-lockfile

      - name: Check
        run: vp check

      - name: Check Types
        run: vp run check-types

      - name: Run Knip
        run: vp exec knip --reporter github-actions

      - name: Run Build
        run: vp run build
