name: React Doctor

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  react-doctor:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run React Doctor
        uses: millionco/react-doctor@v2
